<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>0.6.0-beta</Version>
        <TargetFramework>net6.0</TargetFramework>

        <ModFolderName>$(MOD_NAME)</ModFolderName>
    </PropertyGroup>

    <Import Project="..\TowerCore\TowerCore.msbuild" />

    <ItemGroup>
        <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
    </ItemGroup>
</Project>
